# -*- coding: utf-8 -*-
"""Umap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12wtMYe-1L1BCb5PTKMUJT0Bz-uKAONKS
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import umap

# Used to get the data
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

# Some plotting libraries
import matplotlib.pyplot as plt
# %matplotlib inline
from bokeh.plotting import show, save, output_notebook, output_file
from bokeh.resources import INLINE
output_notebook(resources=INLINE)

pip install umap-learn

categories = ['rec.motorcycles','soc.religion.christian','rec.sport.hockey','rec.sport.baseball','sci.med']
remove = ('headers', 'footers', 'quotes')
twenty_groups = fetch_20newsgroups(subset='all', shuffle=True, random_state=42, categories = categories, remove = remove )
category_labels = [twenty_groups.target_names[x] for x in twenty_groups.target]
hover_df = pd.DataFrame(category_labels, columns=['categories'])

vectorizer = CountVectorizer(min_df=5, stop_words='english')
word_doc_matrix = vectorizer.fit_transform(twenty_groups.data)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# embedding = umap.UMAP(n_components=2, metric='hellinger').fit(word_doc_matrix)

!pip install umap-learn[plot]

import umap.plot

f = umap.plot.points(embedding, labels=hover_df['categories'])